# Generated by Django 4.2.1 on 2023-05-14 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='Pics')),
                ('Flipkart_Price', models.IntegerField()),
                ('Amazon_Price', models.IntegerField()),
            ],
        ),
    ]
